project '沃克家.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target '沃克家' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 沃克家
pod 'MBProgressHUD'
end
